version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.1.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          mapping: |
            content/.* update_website true
            iac/.* update_infrastructure true
            sass/.* update_website true
            static/.* update_website true
            syntaxes/.* update_website true
            templates/.* update_website true
            themes/.* update_website true
