# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  zola: jerus-org/zola@1.2.3
  toolkit: digital-prstv/circleci-toolkit@2.7.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
parameters:
  update-infrastructure:
    type: boolean
    default: false
    description: Update the site infrastructure
  update-website:
    type: boolean
    default: false
    description: |
      Build the website using zola. 
      Copy to the internet when run on the main branch.
  validation-flag:
    type: boolean
    default: false
    description: |
      If set to true, the generate-config workflow will be triggered.
  update-changelog:
    type: boolean
    default: false
    description: |
      If set to true, the update-changelog workflow will be triggered.
  min-rust-version:
    type: string
    default: "1.81"
  fingerprint:
    type: string
    default: "SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_website:
    when: << pipeline.parameters.update-website >>
    jobs:
      - zola/build:
          zola_version: 0.19.2
          list_directory: true
          pre-steps:
            - attach_workspace:
                at: /home/circleci/
          post-steps:
            - persist_to_workspace:
                root: /home/circleci/
                paths:
                  - project/public
      - toolkit/bluesky:
          filters:
            branches:
              ignore: main
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min-rust-version >>
          pcu_verbosity: "-vvv"
          command: "draft"
          context:
            - release
            - bot-check
            - pcu-app
            - bluesky
          requires:
            - zola/build
          post-steps:
            - persist_to_workspace:
                root: /home/circleci/
                paths:
                  - project/bluesky

      - toolkit/update_changelog:
          filters:
            branches:
              ignore: main
          requires:
            - toolkit/bluesky
          context:
            - release
            - bot-check
            - pcu-app
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min-rust-version >>

  update_changelog:
    when: << pipeline.parameters.update-changelog >>
    jobs:
      - toolkit/update_changelog:
          filters:
            branches:
              ignore: main
          context:
            - release
            - bot-check
            - pcu-app
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min-rust-version >>
      - toolkit/end_success:
          message: "Changelog update already completed in PR."
          filters:
            branches:
              only: main
