version: 2.1
setup: true
orbs:
  aws-cli: circleci/aws-cli@5.3.3
  terraform: circleci/terraform@3.6.0
parameters:
  success-flag:
    type: boolean
    default: false
    description: |
      If set to true, the success workflow will be triggered.
  validation-flag:
    type: boolean
    default: false
    description: |
      If set to true, the generate-config workflow will be triggered.
  release-website:
    type: boolean
    default: false
    description: |
      If set to true, the release-website workflow will be triggered.
  deploy-iac:
    type: boolean
    default: false
    description: |
      If set to true, the deploy-iac workflow will be triggered.
  min-rust-version:
    type: string
    default: "1.81"
  fingerprint:
    type: string
    default: "SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg"

jobs:
  authorise_aws:
    docker:
      - image: cimg/base:2025.05
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: arn:aws:iam::086010417807:role/CircleCI-Digital-PRSTV
          region: eu-west-1
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .aws
  plan-01-remote:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/01-remote
          backend_config_file: ../remote.config

  apply-01-remote:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/apply:
          path: ./iac/01-remote
          backend_config_file: ../remote.config

  plan-10-static:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/10-static
          backend_config_file: ../remote.config

  apply-10-static:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/apply:
          path: ./iac/10-static
          backend_config_file: ../remote.config

  plan-20-network:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/20-network
          backend_config_file: ../remote.config

  apply-20-network:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/apply:
          path: ./iac/20-network
          backend_config_file: ../remote.config

  plan-21-site-cert:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/21-site-cert
          backend_config_file: ../remote.config

  apply-21-site-cert:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/apply:
          path: ./iac/21-site-cert
          backend_config_file: ../remote.config

  plan-22-sec-headers:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/22-sec-headers
          backend_config_file: ../remote.config

  apply-22-sec-headers:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - run: zip -j ./iac/22-sec-headers/javascript.zip ./iac/22-sec-headers/index.js
      - terraform/apply:
          path: ./iac/22-sec-headers
          backend_config_file: ../remote.config

  plan-30-edge:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/30-edge
          backend_config_file: ../remote.config

  apply-30-edge:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/apply:
          path: ./iac/30-edge
          backend_config_file: ../remote.config

workflows:
  deploy_iac:
    when:
      and:
        - not: << pipeline.parameters.success-flag >>
        - not: << pipeline.parameters.validation-flag >>
        - not: << pipeline.parameters.release-website >>
        - << pipeline.parameters.deploy-iac >>

    jobs:
      - authorise_aws
      - plan-01-remote:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-10-static:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-20-network:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-21-site-cert:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-22-sec-headers:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-30-edge:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - apply-01-remote:
          context:
            - AWS-DEV
          requires:
            - plan-01-remote
            - plan-10-static
            - plan-20-network
            - plan-21-site-cert
            - plan-22-sec-headers
            - plan-30-edge
      - apply-10-static:
          context:
            - AWS-DEV
          requires:
            - apply-01-remote
      - apply-20-network:
          context:
            - AWS-DEV
          requires:
            - apply-01-remote
      - apply-21-site-cert:
          context:
            - AWS-DEV
          requires:
            - apply-20-network
      - apply-22-sec-headers:
          context:
            - AWS-DEV
          requires:
            - apply-01-remote
      - apply-30-edge:
          context:
            - AWS-DEV
          requires:
            - apply-10-static
            - apply-21-site-cert
            - apply-22-sec-headers
