# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  terraform: circleci/terraform@3.6.0
  aws-cli: circleci/aws-cli@5.3.2
  toolkit: digital-prstv/circleci-toolkit@2.9.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
parameters:
  update-infrastructure:
    type: boolean
    default: false
    description: Update the site infrastructure
  update-website:
    type: boolean
    default: false
    description: |
      Build the website using zola. 
      Copy to the internet when run on the main branch.
  validation-flag:
    type: boolean
    default: false
    description: |
      If set to true, the generate-config workflow will be triggered.
  update-changelog:
    type: boolean
    default: false
    description: |
      If set to true, the update-changelog workflow will be triggered.
  min-rust-version:
    type: string
    default: "1.81"
  fingerprint:
    type: string
    default: "SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg"

jobs:
  authorise_aws:
    docker:
      - image: cimg/base:2025.05
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: arn:aws:iam::086010417807:role/CircleCI-Digital-PRSTV
          region: eu-west-1
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .aws
  plan-01-remote:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/01-remote
          backend_config_file: ../remote.config

  plan-10-static:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/10-static
          backend_config_file: ../remote.config

  plan-20-network:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/20-network
          backend_config_file: ../remote.config

  plan-21-site-cert:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/21-site-cert
          backend_config_file: ../remote.config

  plan-22-sec-headers:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/22-sec-headers
          backend_config_file: ../remote.config

  plan-30-edge:
    docker:
      - image: cimg/base:2025.05
    executor: terraform/default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/
      - terraform/install
      - terraform/plan:
          path: ./iac/30-edge
          backend_config_file: ../remote.config

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  iac-validation:
    when: << pipeline.parameters.update-infrastructure >>
    jobs:
      - authorise_aws
      - plan-01-remote:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-10-static:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-20-network:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-21-site-cert:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-22-sec-headers:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - plan-30-edge:
          context:
            - AWS-DEV
          requires:
            - authorise_aws
      - toolkit/update_changelog:
          branches:
            ignore: main
          requires:
            - plan-30-edge
          context:
            - release
            - bot-check
            - pcu-app
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min-rust-version >>
