version: 2.1
setup: true
orbs:
  zola: jerus-org/zola@1.2.3
  toolkit: digital-prstv/circleci-toolkit@2.8.3
  aws-cli: circleci/aws-cli@5.3.1
parameters:
  min-rust-version:
    type: string
    default: "1.81"
  fingerprint:
    type: string
    default: SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg
commands:
  bsky:
    description: >
      Execute bluesky draft or post commands.

    parameters:
      command:
        type: enum
        default: draft
        enum:
          - draft
          - post
      pcu_verbosity:
        type: string
        default: "-vv"
      blog_directory:
        type: string
        default: "content/blog"

    steps:
      - run:
          name: Execute bluesky command `<< parameters.command >>`
          command: |
            set -exo pipefail

            if [ "<< parameters.command >>" == "draft" ] ; then
              echo "Drafting a new post"
              pcu << parameters.pcu_verbosity >> bsky draft << parameters.blog_directory >>
            elif [ "<< parameters.command >>" == "post" ] ; then
              echo "Posting a new post"
              pcu << parameters.pcu_verbosity >> bsky post
            fi

jobs:
  update_site:
    executor: aws-cli/default

    steps:
      - aws-cli/setup:
          role_arn: arn:aws:iam::086010417807:role/CircleCI-Digital-PRSTV
          region: eu-west-1
      - run:
          # Deploy to S3 using the sync command
          name: Deploy to S3
          command: aws s3 sync --delete /tmp/workspace/public s3://www.jrussell.ie

  bluesky:
    description: >
      Execute bluesky draft or post commands.

    executor:
      name: toolkit/base_env

    parameters:
      ssh_fingerprint:
        type: string
        description: |
          The fingerprint of the ssh key to use
      command:
        type: enum
        default: draft
        enum:
          - draft
          - post
      pcu_verbosity:
        type: string
        default: "-vv"
      blog_directory:
        type: string
        default: "content/blog"
      remove_ssh_key:
        type: boolean
        default: true
        description: "Remove the original SSH key from the agent"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - <<parameters.ssh_fingerprint>>
      - when:
          condition: << parameters.remove_ssh_key >>
          steps:
            - run:
                name: Remove original SSH key from agent
                command: |
                  ssh-add -l
                  ssh-add -d ~/.ssh/id_rsa.pub
                  ssh-add -l
      - toolkit/gpg_key
      - toolkit/git_config
      - run:
          name: Install Latest pcu
          command: |
            set -exo pipefail

            cargo install --git  https://github.com/jerus-org/pcu.git

      - bsky:
          command: << parameters.command >>
          pcu_verbosity: << parameters.pcu_verbosity >>
          blog_directory: << parameters.blog_directory >>

workflows:
  release_website:
    jobs:
      - zola/build:
          zola_version: 0.19.2
          list_directory: true
          check_links: false
          output_dir: /tmp/workspace/public
          pre-steps:
            - attach_workspace:
                at: /tmp/workspace
          post-steps:
            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                  - public
      - bluesky:
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          command: post
          pcu_verbosity: "-vvv"
          remove_ssh_key: false
          context:
            - release
            - bot-check
            - pcu-app
            - bluesky

      - update_site:
          context:
            - AWS-DEV
          requires:
            - zola/build
          pre-steps:
            - attach_workspace:
                at: /tmp/workspace

      - toolkit/save_next_version:
          requires:
            - update_site
            - bluesky
          min_rust_version: << pipeline.parameters.min-rust-version >>

      - toolkit/make_release:
          name: website github release
          context:
            - release
            - bot-check
          requires:
            - toolkit/save_next_version
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min-rust-version >>
          when_cargo_release: false
          pcu_update_changelog: true
      - toolkit/no_release:
          min_rust_version: << pipeline.parameters.min-rust-version >>
          requires:
            - toolkit/save_next_version:
                - failed
