version: 2.1
setup: true
orbs:
  zola: jerus-org/zola@1.3.0
  toolkit: digital-prstv/circleci-toolkit@4.1.0
  aws-cli: circleci/aws-cli@5.4.1
parameters:
  min_rust_version:
    type: string
    default: "1.81"
  fingerprint:
    type: string
    default: SHA256:OkxsH8Z6Iim6WDJBaII9eTT9aaO1f3eDc6IpsgYYPVg

jobs:
  update_site:
    executor: aws-cli/default

    steps:
      - aws-cli/setup:
          region: eu-west-1
          role_arn: ${AWS_ROLE_ARN}
      - run:
          # Deploy to S3 using the sync command
          name: Deploy to S3
          command: aws s3 sync --delete /tmp/workspace/public s3://www.jrussell.ie

  update_company_site:
    executor: aws-cli/default

    steps:
      - aws-cli/setup:
          region: eu-west-1
          role_arn: ${AWS_ROLE_ARN}
      - run:
          name: Deploy to company S3
          command: aws s3 sync --delete /tmp/workspace/public-company s3://www.jerusdataprotection.ie

workflows:
  release_website:
    jobs:
      - zola/build:
          zola_version: 0.19.2
          list_directory: true
          check_links: false
          output_dir: /tmp/workspace/public
          pre-steps:
            - attach_workspace:
                at: /tmp/workspace
          post-steps:
            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                  - public

      - update_site:
          context:
            - AWS-DEV
          requires:
            - zola/build
          pre-steps:
            - attach_workspace:
                at: /tmp/workspace

      - zola/build:
          name: build_company
          zola_version: 0.19.2
          config: config.jerusdataprotection.toml
          check_links: false
          output_dir: /tmp/workspace/public-company
          pre-steps:
            - attach_workspace:
                at: /tmp/workspace
          post-steps:
            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                  - public-company

      - update_company_site:
          context:
            - AWS-COMPANY
          requires:
            - build_company
          pre-steps:
            - attach_workspace:
                at: /tmp/workspace

      - toolkit/save_next_version:
          requires:
            - update_site
          min_rust_version: << pipeline.parameters.min_rust_version >>

      - toolkit/make_release:
          name: website github release
          context:
            - release
            - bot-check
            - pcu-app
            - bluesky
          requires:
            - toolkit/save_next_version
          ssh_fingerprint: << pipeline.parameters.fingerprint >>
          min_rust_version: << pipeline.parameters.min_rust_version >>
          when_cargo_release: false
          when_update_pcu: true
          pcu_verbosity: "-vvvv"
          pcu_update_prlog: true
          remove_ssh_key: false
          when_bluesky: true
          bluesky_command: "post"
      - toolkit/no_release:
          min_rust_version: << pipeline.parameters.min_rust_version >>
          requires:
            - toolkit/save_next_version:
                - failed
